name: Clouding Frontend CD

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: 'Version of jq to install'
        default: '1.7'
      force:
        type: boolean
        required: false
        description: 'Do not check for existing jq installation before continuing.'
        default: false
  push:
    branches:
      - main

jobs:
#
  prepare:
    name: Get Short SHA of commit and get parameters from parameter store
    runs-on: ubuntu-latest
    env:
      PARAMETER_STORE_TOKEN: ${{ secrets.AGENT_PARAMETER_STORE }}
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '${{ inputs.version }}'
          force: '${{ inputs.force }}'
      - uses: actions/checkout@v2
      - name: get SHORT_SHA
        id: get_sha
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=$SHORT_SHA"
      - name: Get parameters from parameter store
          ./scripts/get-parameters.sh -o .env && cat .env
    outputs:
      SHORT_SHA: ${{ steps.get_sha.outputs.SHORT_SHA }}
#
  build-test:
    runs-on: ubuntu-latest
    needs: [prepare]
    env:
      SHORT_SHA: ${{ needs.prepare.outputs.SHORT_SHA }}
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VER }}
      - name: Caching node modules # get cache hash file in runner
        id:  node-modules-cache 
        uses: actions/cache@v3
        with:
          path: node_modules
          key: clouding-frontend-${{ runner.os }}-node_modules-cache-restore-key-from-package.json-${{ hashFiles('**/package.json') }}
          restore-keys: |
            clouding-frontend-${{ runner.os }}-node_modules-cache-restore-key-from-package.json-${{ hashFiles('**/package.json') }}

      - name: check env file
        env:
          PROJECT_NAME: ${{vars.PROJECT_NAME}}
          PROJECT_URL: ${{vars.PROJECT_URL}}
          PROJECT_BASE_URL: ${{vars.PROJECT_BASE_URL}}
        run: |
          echo "REACT_APP_PROJECT_NAME=$PROJECT_NAME" >> .env
          echo "REACT_APP_PROJECT_URL=$PROJECT_URL" >> .env
          echo "REACT_APP_PROJECT_BASE_URL=$PROJECT_BASE_URL" >> .env
          cat .env
          ls -la


      - name: Install dependencies
        #if cache is true then skip npm i, else run npm i
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn 
      - name: Build
        run: CI=false yarn build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and publish Docker image to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile 
          push: true
          tags: |
            ghcr.io/chienduynguyen1702/parameter-store-fe:${{ env.SHORT_SHA }}
            ghcr.io/chienduynguyen1702/parameter-store-fe:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
#
  deploy:
    name: Deploy to remote server
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/${{ secrets.SERVER_USERNAME }}/${{ secrets.SERVER_FOLDER }}
          ./docker-compose-restart-fe.sh
          # . ./export-token.sh  && ./get-parameters.sh  -o .env  
